// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type CharacterCount struct {
	ID              uuid.UUID
	StringID        uuid.UUID
	Character       string
	UniqueCharCount int32
}

type Text struct {
	ID           uuid.UUID
	Value        string
	Length       int32
	IsPalindrome bool
	WordCount    int32
	Sha256Hash   string
	CreatedAt    time.Time
}
