// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: texts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createCharCount = `-- name: CreateCharCount :exec
INSERT INTO character_count (id, string_id, character, char_count)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3
)
`

type CreateCharCountParams struct {
	StringID  uuid.UUID
	Character string
	CharCount int32
}

func (q *Queries) CreateCharCount(ctx context.Context, arg CreateCharCountParams) error {
	_, err := q.db.ExecContext(ctx, createCharCount, arg.StringID, arg.Character, arg.CharCount)
	return err
}

const createText = `-- name: CreateText :one
INSERT INTO texts (id, value, length, is_palindrome, word_count, sha256_hash, created_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW()
)
RETURNING id
`

type CreateTextParams struct {
	Value        string
	Length       int32
	IsPalindrome bool
	WordCount    int32
	Sha256Hash   string
}

func (q *Queries) CreateText(ctx context.Context, arg CreateTextParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createText,
		arg.Value,
		arg.Length,
		arg.IsPalindrome,
		arg.WordCount,
		arg.Sha256Hash,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteText = `-- name: DeleteText :exec
DELETE FROM texts
WHERE id = $1
`

func (q *Queries) DeleteText(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteText, id)
	return err
}

const getText = `-- name: GetText :one
SELECT value 
FROM texts WHERE value = $1
`

func (q *Queries) GetText(ctx context.Context, value string) (string, error) {
	row := q.db.QueryRowContext(ctx, getText, value)
	err := row.Scan(&value)
	return value, err
}
