// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: texts.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCharCount = `-- name: CreateCharCount :exec
INSERT INTO character_count (id, string_id, character, unique_char_count)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3
)
`

type CreateCharCountParams struct {
	StringID        uuid.UUID
	Character       string
	UniqueCharCount int32
}

func (q *Queries) CreateCharCount(ctx context.Context, arg CreateCharCountParams) error {
	_, err := q.db.ExecContext(ctx, createCharCount, arg.StringID, arg.Character, arg.UniqueCharCount)
	return err
}

const createText = `-- name: CreateText :one
INSERT INTO texts (id, value, length, is_palindrome, word_count, sha256_hash, created_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW()
)
RETURNING id
`

type CreateTextParams struct {
	Value        string
	Length       int32
	IsPalindrome bool
	WordCount    int32
	Sha256Hash   string
}

func (q *Queries) CreateText(ctx context.Context, arg CreateTextParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createText,
		arg.Value,
		arg.Length,
		arg.IsPalindrome,
		arg.WordCount,
		arg.Sha256Hash,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteTextWithID = `-- name: DeleteTextWithID :exec
DELETE FROM texts
WHERE id = $1
`

func (q *Queries) DeleteTextWithID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTextWithID, id)
	return err
}

const deleteTextWithValue = `-- name: DeleteTextWithValue :exec
DELETE FROM texts
WHERE value = $1
`

func (q *Queries) DeleteTextWithValue(ctx context.Context, value string) error {
	_, err := q.db.ExecContext(ctx, deleteTextWithValue, value)
	return err
}

const getAllTexts = `-- name: GetAllTexts :many
SELECT id, value, length, is_palindrome, word_count, sha256_hash, created_at 
FROM texts 
ORDER BY created_at DESC
`

func (q *Queries) GetAllTexts(ctx context.Context) ([]Text, error) {
	rows, err := q.db.QueryContext(ctx, getAllTexts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Text
	for rows.Next() {
		var i Text
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Length,
			&i.IsPalindrome,
			&i.WordCount,
			&i.Sha256Hash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacterCountsByID = `-- name: GetCharacterCountsByID :many
SELECT character, unique_char_count
FROM texts
JOIN character_count ON $1 = character_count.string_id
ORDER BY character
`

type GetCharacterCountsByIDRow struct {
	Character       string
	UniqueCharCount int32
}

func (q *Queries) GetCharacterCountsByID(ctx context.Context, stringID uuid.UUID) ([]GetCharacterCountsByIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterCountsByID, stringID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCharacterCountsByIDRow
	for rows.Next() {
		var i GetCharacterCountsByIDRow
		if err := rows.Scan(&i.Character, &i.UniqueCharCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilteredTexts = `-- name: GetFilteredTexts :many
SELECT DISTINCT
    t.id,
    t.value,
    t.length,
    t.is_palindrome,
    t.word_count,
    t.sha256_hash,
    t.created_at
FROM texts t
WHERE 
    t.is_palindrome = $1 AND
    t.length >= $2 AND
    t.length <= $3 AND
    t.word_count = $4 AND
    t.value LIKE '%' || $5 || '%'
ORDER BY t.created_at DESC
`

type GetFilteredTextsParams struct {
	IsPalindrome      bool
	MinLength         int32
	MaxLength         int32
	WordCount         int32
	ContainsCharacter sql.NullString
}

func (q *Queries) GetFilteredTexts(ctx context.Context, arg GetFilteredTextsParams) ([]Text, error) {
	rows, err := q.db.QueryContext(ctx, getFilteredTexts,
		arg.IsPalindrome,
		arg.MinLength,
		arg.MaxLength,
		arg.WordCount,
		arg.ContainsCharacter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Text
	for rows.Next() {
		var i Text
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Length,
			&i.IsPalindrome,
			&i.WordCount,
			&i.Sha256Hash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getText = `-- name: GetText :one
SELECT id, value, length, is_palindrome, word_count, sha256_hash, created_at 
FROM texts WHERE value = $1
`

func (q *Queries) GetText(ctx context.Context, value string) (Text, error) {
	row := q.db.QueryRowContext(ctx, getText, value)
	var i Text
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.Length,
		&i.IsPalindrome,
		&i.WordCount,
		&i.Sha256Hash,
		&i.CreatedAt,
	)
	return i, err
}

const getTextByID = `-- name: GetTextByID :one
SELECT id, value, length, is_palindrome, word_count, sha256_hash, created_at 
FROM texts WHERE id = $1
`

func (q *Queries) GetTextByID(ctx context.Context, id uuid.UUID) (Text, error) {
	row := q.db.QueryRowContext(ctx, getTextByID, id)
	var i Text
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.Length,
		&i.IsPalindrome,
		&i.WordCount,
		&i.Sha256Hash,
		&i.CreatedAt,
	)
	return i, err
}
